config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' } # Use your custom registrations controller

  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show create new] do
      resources :likes, only: [:create]
      resources :comments, only: %i[create new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :post

  after_create :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  has_many :likes
  has_many :comments

  after_create :update_user_post_count
  after_create :recent_comments

  def update_user_post_count
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  alias_attribute :comments_count, :comments_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  after_create :recent_posts
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || users_path
  end

  private

  def set_current_user
    @current_user = current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(post_id: @post.id, user_id: current_user.id)

    if @like.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: "Can't create another like"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: :comments).find(params[:user_id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 3)
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @comments = @post.comments
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users/confirmations_controller.rb
module Users
  class ConfirmationsController < Devise::ConfirmationsController
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
  end
end

app/controllers/users/unlocks_controller.rb
module Users
  class UnlocksController < Devise::UnlocksController
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= stylesheet_link_tag('index') %>
<div class="comment-container">
    <h3>Add a new Comment</h3>
    <div class="comment-form">
      <%= form_with model: @comment, url: user_post_comments_path do |form| %>
        <%= form.label :text %>
        <%= form.text_field :text %><br>

        <%= form.hidden_field :post_id, value: params[:post_id] %>
        <%= form.submit "Submit"%>
      <% end %>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :text %>
  <%= form.text_area :text %>
  <%= form.submit "Add post" %>
<% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag('index') %>
<%= render 'shared/user', user:@user %>

<div class="posts-index">
  <% @posts.each do |post| %>
    <div>
      <h3> <%= link_to post.title, user_post_path(@user,post) %></h3>
      <%= render 'shared/post', post: post %>
      <%= render 'shared/comment', comments: post.recent_comments %>
    </div>
  <% end %>
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="comment-container">
  <h1>Add a new post</h1>
  <div class="comment-form">
    <%= form_with model: @post, url: user_posts_path do |form| %>
      <%= form.label :title%>
      <%= form.text_field :title%><br>

      <%= form.label :text%>
      <%= form.text_area :text, cols:50, row: 50 %><br>
      <%= form.submit "Add post" %>
    <% end %>
  </div>
</div>

app/views/posts/new_post.html.erb
<%= form_with model: @post, url: user_posts_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :text %>
  <%= form.text_area :text %>
  <%= form.submit "Add post" %>
<% end %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag('index') %>
<div class="post-details">
  <span>
    <h1> <%= @post.title %> by <%= @user.name %> </h1>
  </span>
  <p> <%= @post.text %> </p>
  <p>
    <%= link_to 'Comment on this post', new_user_post_comment_path(user_id: current_user.id, post_id: @post.id) %>
  </p>
  <span>Comments: <%= @post.comments_count %> Likes: <%= @post.likes_counter %> </span>
  </span>
  <p> <%= @post.text %>
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |l| %>
      <%= l.submit  "Like", class: ["new-post-btn submit-btn"] %>
    <% end %>
  <%= render 'shared/comment', comments: @comments %>
</div>

app/views/users/index.html.erb
<div class="btn">
<h1>BLOG APP</h1>
    <button>
      <%= link_to 'Create new post', new_user_post_path(current_user) %>
    </button>
  </div> 
<% @users.each do |user| %>
  <%= render 'shared/user', user:user %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/user', user:@user %>

<div class="post-container">
  <div class="post-heading">
    <h2>About me</h2>
    <p><%= @user.bio %></p>
  </div>
  <% @posts.each do |post| %>
    <div class="post-title">
      <h4>Post</h4>
      <h3> <%= link_to post.title, user_post_url(@user, post) %> </h3>
      <%= render 'shared/post', post:post %>
    </div>
  <% end %> 
  <button> <%= link_to "See all posts", user_posts_path(@user) %></button>
</div>